version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: satsclub_postgres
    environment:
      POSTGRES_DB: satsclub
      POSTGRES_USER: satsclub_user
      POSTGRES_PASSWORD: satsclub_password
    ports:
      - "5477:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: 